apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-replicas   #Наавание деплоймента 
  labels: 
    app: my-k8s-aplication
    env: prod
    owner: DimaViediernikov
spec:                       #С какими подами будет работать деплоймент, с соответствующими лейблам 
  replicas: 2               #Количество реплик
  selector:
    matchLabels:
      project: cia          #лейбл
  template:                 #Описание пода
    metadata:
      labels:
        project: cia
    spec:                 #Спецификация пода
      conteiners:
        - name: cia-meb
          image: adv4000/k8sphp:vesion1
          ports:
            - containerPort: 80
