apiVersion: networking.k8s.io/v1beta1
kind: ingress
metadata:
  name: ingress-hist   #Наавание деплоймента 
  
spec:                       #С какими подами будет работать деплоймент, с соответствующими лейблам 
  rules:
  - host:                    #Имя хоста с домен именем
    http:
      paths:
        - backend:
            serviceName:        #Название сервиса на кокой переводить трафик 
            servicePort: 80     #порт приложения

  - host:                    
    http:
      paths:
        - backend:
            serviceName:       
            servicePort: 80

  - host:                    
    http:
      paths:
        - backend:
            serviceName:        
            servicePort: 80