apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    emv: prod
    app: main
    tier: fronntend
    owner: DinaViediernikov
spec:
  containers:
  - name: container-apache
    image: nginx:latest
    ports:
      - containerPort: 80
